### ISSUE TITLE
Push git repository encounter `self.param_types.len() <= (u16::MAX as usize)` error

### ISSUE THREAD

**Issue by genedna** [open-rust-initiative/mega#186]
I cloned the repo form `https://github.com/biomejs/biome.git,` then added a remote `git remote add local http://127.0.0.1:8000/third_parts/crates/biomejs/biome`. When I push, I encounter this error:

```bash
thread 'tokio-runtime-worker' panicked at /Users/eli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-postgres-0.7.1/src/message/parse.rs:31:13:
assertion failed: self.param_types.len() <= (u16::MAX as usize)
```

**Comment by benjamin-747** [comment]
This issue was caused by the parameter length of the paser in sea-orm being to long , which exceed 65536, split the batch query into 1000 obj each query will solve this problem

**Comment by genedna** [comment]
@benjamin-747 ,

Do you mean `GIT_INTERNAL_DECODE_STORAGE_BATCH_SIZE` value set to `1000` in the `.env`?

```config
GIT_INTERNAL_DECODE_CACHE_SIZE = 1000 # Maximum number of git objects in LRU cache
GIT_INTERNAL_DECODE_STORAGE_BATCH_SIZE = 1000 # The maximum number of git objects in a "INSERT" SQL database operation
GIT_INTERNAL_DECODE_STORAGE_TQUEUE_SIZE = 10 # The maximum number of parallel insertion threads in the database operation queue
```
