### ISSUE TITLE
Question about starting project

### ISSUE THREAD

**Issue by TuGang-Git** [open-rust-initiative/mega#268]
I want to start your project on Windows. I followed your guidance in README and got stuck in step 5 "Config environment variables for local test". I was confusing about what the .env file is, where and what to set 'environment variables such as DB_USERNAME, DB_SECRET, and DB_HOST' and where I should put the following parameter settings.

**Comment by benjamin-747** [comment]
Hi @TuGang-Git ,
The .env file is located at the root path of the project. If it's just for local testing and not for deployment, you can replace the DB_USERNAME in the .env file with the actual value.
