### ISSUE TITLE
There is no README.md in default initial root directory.

### ISSUE THREAD

**Issue by YutingNie** [open-rust-initiative/mega#302]
I am trying to build the UI of mega, but I need a REAEME.md file to test and presentation effects.
Please add a README.md file in default initial root directory. 

```
## Init directory configuration
MEGA_INIT_DIRS = "projects,docs,third_parts" # init these repo directories in mega init command
```

**Comment by benjamin-747** [comment]
hi @YutingNie, this configuration is used to init directory for repo storage, if you want a readme file for testing, you can push one of your repo to mega server by following the next steps:

- first add  an new repositories url in your repo: `git remote add local http://localhost:8000/projects/mega.git`
- using git push to push data to server: `git push local main`

**Comment by genedna** [comment]
@benjamin-747 ，

During the initial setup, including a README.md as part of the initial commit in the root directory would be beneficial. This file can contain essential information about the Mega, offering guidance on how to use it effectively. The content can be designed to help developers quickly understand how to interact with the UI after initialization, providing a clear and concise introduction to the project.

Additionally, it might be helpful to encourage users to customize the README.md file. This could include adding specific information relevant to their implementation or any agreed-upon standards and practices within their development team. Allowing such flexibility would make README.md more useful for individual projects and foster a sense of community contribution and customization.

These steps could significantly enhance the user experience from the project's setup phase, making it easier for developers to get up to speed and contribute more effectively.

**Comment by genedna** [comment]
@YutingNie ,

After a thorough discussion within @benjamin-747, we've identified a significant problem in the design of Mega. Specifically, the current implementation fails to differentiate between the importation codebase of git and the codebase in the monorepo. This oversight has led to some functional deficiencies in our system.

We're just letting you know that we need a fix to fix this issue. @benjamin-747 is now prioritizing this matter and working diligently to resolve it. Once the necessary repairs are made, we can support this functionality appropriately.

Also, we are aligning our efforts with the requirements outlined in issue #34. This involves the creation of comprehensive documentation to assist developers in swiftly deploying and utilizing Mega. We aim to provide clear, detailed guides that will not only facilitate the use of Mega but also encourage contributions to its features and capabilities.
