### ISSUE TITLE
Quick start manual and .env should be updated 

### ISSUE THREAD

**Issue by yyk808** [open-rust-initiative/mega#369]
Hi, everyone.
During my first setting up, I found that the manual didn't catch up with the latest code. Some of the env variables were left out. Here they are.

1. MEGA_LFS_OBJ_LOCAL_PATH. If not properly set, the log will show:
```log
2024-04-17T09:25:46.419820Z DEBUG request{method=GET uri=/third-part/linux.git/info/refs?service=git-receive-pack version=HTTP/1.1}: tower_http::trace::on_request: started processing request
thread 'tokio-runtime-worker' panicked at gateway/src/https_server.rs:74:53:
called `Result::unwrap()` on an `Err` value: NotPresent
```
I'm not quite sure if it's ok to just leave it unset, but given a default value or asking user to set should be better.

2. MEGA_SSH_KEY, log shows:
```log
thread 'tokio-runtime-worker' panicked at gateway/src/ssh_server.rs:109:52:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
plus, this function checks the existence of the target directory, but won't create it.

3. CLEAN_CACHE_AFTER_DECODE
```log
thread 'tokio-runtime-worker' panicked at ceres/src/pack/handler.rs:157:14:
called `Result::unwrap()` on an `Err` value: NotPresent
```

May I make a PR to update the doc and fix them?

**Comment by benjamin-747** [comment]
hi, @yyk808
Thank you very much for your suggestion. Currently, the .env configuration file contains the three variables you mentioned, but the documentation file has not been updated. Please feel free to make pr and fix it. 😃
