### ISSUE TITLE
Proposal for a New URL Protocol for Sharing Open Source Projects in DHT (Distributed Hash Table)

### ISSUE THREAD

**Issue by genedna** [open-rust-initiative/mega#53]
### Proposal

I propose developing a new URL protocol for Git to share open source projects in a DHT(Distributed Hash Table). The benefits of leveraging DHT include enhanced reliability, fault tolerance, and scalability. Given these advantages, a specific URL protocol for this purpose would significantly advance how developers collaborate on open source projects.

### Expected Benefits

1. Scalability: With DHT, the new URL protocol can handle more projects than current solutions.
2. Reliability: The DHT's inherent redundancy ensures that projects remain accessible even if several nodes go down.
3. Decentralization: This protocol would enhance open source openness by making projects less reliant on centralized platforms.

**Comment by genedna** [comment]
@wujian0327 and @benjamin-747,

The original Git protocol syntax is:

```
[<protocol>://]<username>[:<password>]@<hostname>[:<port>]/<path>[.git]
```

For a p2p Git protocol in Mega:

1. The `<protocol>` could be an optional prefix like `p2p://` or `mega://` to indicate the p2p protocol.
2. The `<username>` represents the node key accessing the repository so that we could replace it with <key> for the p2p identity.
3. The `<password>` is unnecessary for public repositories. Authentication could be designed separately per #57.
4. The `<hostname>` typically represents the server, but in p2p, it maps to the node key hosting the repo. We could reuse `<key>` here or use a different term like `<hostkey>` to avoid confusion.
5. The `<port>` may not be relevant for p2p networking?
6. For `<path>`, mega uses monorepos so there are no `<namespaces>` or `<repo>` names, only paths. We could design a virtual path scheme to map paths to exposed public paths privately.

Do you know if this looks like the one below?

```
mega://<key>@<host>:<repo>
```

**Comment by wujian0327** [comment]
Here are some results of our discussions：
1. The p2p address of mega is:
```
p2p://<peerId>/<repo>
``` 
for example：p2p://12D3KooWFgpUQa9WnTztcvs5LLMJmwsMoGZcrTHdt9LKYKpM4MiK/abc.git
 - \<peerId> Indicates the address of the p2p node
 - \<repo> Indicates the name of the repository


When a user uploads a repo to mega, we will generate this shareable address for him.

2. How DHT store data:
for example：key=abc.git
value=
```
[
    {
        "upstream":"node_a_peerId",
        "peerId":"node_a_peerId ",
        "hash":"abcdefg",
        "timestamp":1690191636
    },
    {
        "upstream":"node_b_peerId",
        "peerId":"node_a_peerId ",
        "hash":"ddddddd",
        "timestamp":1690128000
    }
]
```

3. Steps to work with address：
   1. mega pull p2p://12D3KooWFgpUQa9WnTztcvs5LLMJmwsMoGZcrTHdt9LKYKpM4MiK/abc.git
   2. get peerId: 12D3KooWFgpUQa9WnTztcvs5LLMJmwsMoGZcrTHdt9LKYKpM4MiK
   3. get nodeAddress by peerId: /ip4/127.0.0.1/tcp/8002/p2p/12D3KooWFgpUQa9WnTztcvs5LLMJmwsMoGZcrTHdt9LKYKpM4MiK
   4. dial peer address
   5. begin to transport the package of abc.git

**Comment by wujian0327** [comment]
todo get_obejct_id
todo pull functiuon
