### ISSUE TITLE
Design and Implement P2P Discovery Ability for Git Based on DHT

### ISSUE THREAD

**Issue by wujian0327** [open-rust-initiative/mega#57]
Git is an excellent and widely used version control system. However, one potential area of improvement lies in the decentralization of repositories. Git collaboration relies heavily on centralized services such as GitHub, GitLab, Bitbucket, etc. We propose adding a peer-to-peer (P2P) discovery feature based on Distributed Hash Table (DHT) technology to further decentralize Git repositories using Mega.

DHT is a class of decentralized distributed systems that provides a lookup service similar to a hash table: (key, value) pairs are stored in a DHT, and any participating node can efficiently retrieve the value associated with a given key.

1. **Design a DHT schema for Git**: This schema would allow Git repositories to be stored and found in a DHT. The key could be a hash of the repository's URL, and the value could be the repository's metadata. 

2. **Integrate DHT into Mega**: Modify Mega to include DHT functionality. This could involve adding or modifying new commands to support DHT operations.

3. **Develop a discovery protocol**: This protocol would enable Git clients to discover each other and exchange repository information via DHT. #53 

This feature could greatly increase the decentralization and resilience of Git, making it even more reliable and versatile for version control.

**Comment by genedna** [comment]
@wujian0327 ,

I design a discovery an open source project through delay and client, isn't OK? 

```mermaid
sequenceDiagram
    autonumber
    participant Client A
    participant Delay
    participant Client B
    Client A->>+Delay: Hello, Delay. I am joined!
    Delay-->>-Client A: Hi Bro, Do you have some projects to go public?
    Client A->>Delay: I have one project named A: {key}/A/{path}.
    loop WriteDHT
        Delay->>Delay: {key}/A/{path}
    end
    Note right of Delay: Write the projects to DHT to broadcast
    Delay-->>Client B: DHT Broadcast
    Client B->>Client A: I need to clone the A:{key}/{path}.
    Client A-->Client B: It's your pack file.
```

**Comment by wujian0327** [comment]
@genedna 
I added some relay server details. 
Perhaps we need to further discuss the definition of DHT's key and value.
 It is also necessary to negotiate the transfer details of git through p2p nodes.
```mermaid
sequenceDiagram
    Client A->>+Relay: Hello Relay.I am joined!
    Relay-->>-Client A: Hi Bro, Do you have some projects to go public?
    Client A->>+Relay: I have one project named A: {key}/A/{path}
    Relay->>+Relay:put key={key}/A/{path}, value=peerId(Client A) to DHT
    Relay->>+Client B: DHT Broadcast
    Client B->>+Client B: get project A address(peerId) from DHT
    Client B->>+Relay: help me connect to Client A
    Relay-->>+Client B: tell Client A public ip address and port
    Relay-->>-Client A: tell Client B public ip address and port
    Client B->>+Client A: I need to clone the A:{key}/{path}
    Client A-->>+Client B: It's your pack file.
```

**Comment by genedna** [comment]
@wujian0327 ,

I agree with you. The key and value of the DHT are important factors to consider, and I think it would be helpful to discuss them in more detail. Since this issue is related to issue #53, I suggest we continue the discussion there.

**Comment by genedna** [comment]
It's a proposal using Nostr and DHT to collaborate. Please review and comment on [Nostr NIP - Decentralize Open Source Collaboration with Customization of the Git P2P Transfer Protocol and Nostr - v1](https://docs.google.com/document/d/1l5KhsYmDXEWTUUaw8B6hC99PYkq6XNZeMsJp1pJ92R4).
