### ISSUE TITLE
Upgrade Lunar to Tauri 2.0

### ISSUE THREAD

**Issue by genedna** [open-rust-initiative/mega#631]
The Tauri already release 2.0, and [Lunar](https://github.com/web3infra-foundation/mega/tree/main/lunar) should upgrade the library.

**Comment by headStyleColorRed** [comment]
Hey there @genedna, may I do this update? 🤓

**Comment by genedna** [comment]
@headStyleColorRed ,

Sorry, it's already in the development through #633 .
