### ISSUE TITLE
Suggestions for improving Mega's performance

### ISSUE THREAD

**Issue by benjamin-747** [open-rust-initiative/mega#68]
Currently, Mega faces the issue of low efficiency in handling large repositories. Here are some potential optimization suggestions:

1. **Adjust the LRU cache size** during unpacking to be dynamically initialized based on the object size, such as 30% of the object size.(Further discussion is needed) This can help reduce the number of cache misses and minimize the need for extensive database queries.

2. During unpacking, git objects are parsed, but when storing the mr objects, the original raw data is used. Then, during the merge of mr objects, they are converted back into git objects, this causing **redundant parsing**. It is possible to consider directly **returning the raw data during unpacking** to avoid this issue.

3. **Maintain a database index** to improve data retrieval speed and overall performance.

4. When building the tree in memory, **load all the required git objects into memory** at once, instead of repeatedly querying the database.

**Comment by Ivanbeethoven** [comment]
From a code level perspective, adjusting the cache size is relatively simple to implement. There is a code demo below. 
```rust
// as for cache
impl ObjectCache {
    pub fn new(size: Option<usize> ) -> Self {
        let lru_size ;
        if let Some(size) = size{
            lru_size = NonZeroUsize::new(size).unwrap();
        }else {
            lru_size = CACHE_SIZE;
        }
        ObjectCache {
            ioffset: HashMap::new(),
            ihash: LruCache::new(lru_size),
            inner: LruCache::new(lru_size),
        }
    }
..........

// as for decode iterator
impl<BR: std::io::BufRead> EntriesIter<BR> {
    //After Pack::check_header
    pub fn new(r: BR, obj_num: u32) -> Self {
        Self {
            inner: r,
            offset: 12,
            objects_left: obj_num,
            cache: ObjectCache::new(Some((obj_num as usize)/10)),
            storage: None,
        }
    }
}

```

**Comment by genedna** [comment]
@benjamin-747 & @Ivanbeethoven ,

Mega utilizes a three-tiered caching model:

The first tier, known as ObjectCache, is a system-generated cache. The number of objects in the Pack file determines the quantity of ObjectCache. For instance, if the Pack file contains many objects, approximately 40% would require dynamic initialization of ObjectCache during parsing.

The second tier involves the use of a Redis service cache. This is particularly beneficial for services with object quantities that exceed a certain threshold. In instances where the ObjectCache is empty, the system queries the Redis service. However, this feature is optional and is only activated when the Redis service URI is provided at the launch of Mega.

The third and final tier is the default database storage for the Mega system. This tier is utilized when the first two tiers are ineffective, resulting in a query to the database. However, this method can significantly impact database performance and is considered the most costly caching method.

```mermaid
graph LR; A[ObjectCache] -- Ineffective --> B[Redis Service Cache]; B -- Ineffective --> C[Database Storage]; style A fill:#f9d,stroke:#333,stroke-width:2px; style B fill:#fc6,stroke:#333,stroke-width:2px; style C fill:#6f9,stroke:#333,stroke-width:2px;
```
