### ISSUE TITLE
Version conflicts between craft’s dependency pgp library and p2p’s dependency libp2p library

### ISSUE THREAD

**Issue by PhyKnife** [open-rust-initiative/mega#94]
PGP 0.10.0 (or its higher version0.10.1,0.10.2) and libp2p 0.51.3 have version conflicts,they depends on different version for `curve25519-dalek` 
Error message is below(PGP 0.10.2 and libp2p 0.51.3):
 error: failed to select a version for `curve25519-dalek`.
    ... required by package `snow v0.9.1`
    ... which satisfies dependency `snow = "^0.9.1"` of package `libp2p-noise v0.42.0`
    ... which satisfies dependency `libp2p-noise = "^0.42.0"` of package `libp2p v0.51.3`
    ... which satisfies dependency `libp2p = "^0.51.3"` of package `p2p v0.1.0 (E:\mega\p2p)`      
    ... which satisfies path dependency `p2p` (locked to 0.1.0) of package `mega v0.1.0 (E:\mega)`
versions that meet the requirements `=4.0.0-rc.0` are: 4.0.0-rc.0

all possible versions conflict with previously selected packages.

  previously selected package `curve25519-dalek v4.0.0-rc.3`
    ... which satisfies dependency `curve25519-dalek = "=4.0.0-rc.3"` of package `ed25519-dalek v2.0.0-rc.3`
    ... which satisfies dependency `ed25519-dalek = "^2.0.0-rc.3"` of package `pgp v0.10.2`        
    ... which satisfies dependency `pgp = "^0.10.2"` of package `git-craft v0.1.0 (E:\mega\craft)`
    ... which satisfies path dependency `git-craft` (locked to 0.1.0) of package `mega v0.1.0 (E:\mega)`

failed to select a version for `curve25519-dalek` which could resolve this conflict

**Comment by wujian0327** [comment]
hello @PhyKnife ,

**Noise in libp2p (v0.51, v0.52) does contain conflicts with PGP (0.10.0).** One needs CURVE25519-DALEK 4.0.0-RC.1 but anouther needs curve25519-dalek v4.0.0-rc.3.

Here are two solutions：
1. Can your project not be written to the Cargo.toml in the root directory?
2. If the first solution is not easy to handle, I will try to replace the noise package.

I will wait for your reply.

**Comment by PhyKnife** [comment]
Hi @wujian0327,

I have tried ur solution 1, but it seems not worked.
Package 'craft' is a part of the project, when I use the first solution, cargo complains that current package believes it's in a workspace when it's not,  
 Any other solutions maybe?

**Comment by PhyKnife** [comment]
Hi, @wujian0327 ,

Thanks for your solution and work. I hope you have not started to replace the noise package in libp2p, today I tried your solution 1 again and it worked. Last time I use a wrong way, my mistake.

I already update lib pgp to v0.10.2, version conflict is fixed, this issue should be closed.
